import type { NextPage } from 'next';
import { useEffect } from 'react';
import { useSession } from 'next-auth/react';
import Head from 'next/head';
import { Header } from '../src/components/Header';
import { Hero } from '../src/components/Hero';
import { ProfileCard } from '../src/components/ProfileCard';
import { saveUser, userExist } from './api/user/utils';

const Home: NextPage = ({ allUsers }: any) => {
    const { data: session } = useSession();

    const loggedInUser = {
        name: session?.user?.name,
        email: session?.user?.email,
        image: session?.user?.image,
    };

    useEffect(() => {
        if (session && !userExist(loggedInUser)) {
            saveUser(loggedInUser);
        }
    }, [session]);

    return (
        <>
            <Head>
                <title>Fitnest</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {/* Header */}
            <Header />

            <div className="mx-12 my-4">
                {session ? <ProfileCard /> : <Hero />}
            </div>
        </>
    );
};

export default Home;
