import type { NextPage } from 'next';
import { useEffect } from 'react';
import { signIn, signOut, useSession } from 'next-auth/react';
import Head from 'next/head';
import { Header } from '@/components/Header';
import { Hero } from '@/components/Hero';
import { ProfileCard } from '@/components/ProfileCard';
import { saveUser, userExist } from './api/user/utils';
import { useRouter } from 'next/router';

const Home: NextPage = ({ allUsers }: any) => {
    const { data: session } = useSession();

    useEffect(() => {
        const loggedInUser = {
            name: session?.user?.name,
            email: session?.user?.email,
            image: session?.user?.image,
        };

        if (session && !userExist(loggedInUser)) {
            saveUser(loggedInUser);
        }
    }, [session]);

    return (
        <>
            <Head>
                <title>Fitnest</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="flex items-center justify-center flex-col ">
                {!session && <Hero />}
            </div>
        </>
    );
};

export default Home;
